# ==== General Configuration ====
# Documentation of the TOML format: https://toml.io/en/latest

# Allow only a single vocabulary (default) or multiple vocabularies in the repository.
single_vocab = false

# ==== Configuration for vocabulary "myvocab" ====

# The name of the vocabulary is used as section name.
# It should match the filename-stem of the vocabulary files.
[vocabs.photocatalysis_example]
# Length of integer IDs in vocabulary. IDs will be left-padded with zeros to specified length.
id_length = 7
# permanent part of IRIs defined in the vocabulary
permanent_iri_part = "https://example.org/"

# Section to configure checks (useful in CI pipeline)
[vocabs.photocatalysis_example.checks]
# Deleting allowed (relevant in CI-pipeline)
allow_delete = false

[vocabs.photocatalysis_example.prefix_map]
ex = "https://example.org/"

# Section of IDranges for coordinating the allocation of numeric ID ranges to
# contributors for each vocabulary. Each idrange contains the same keys:
#
# first_id = <int>            - first reserved integer ID in idrange
# last_id = <int>             - last reserved integer ID in idrange
# gh_name = "<string>"        - user or organisation name on github
# orcid = "<string> or <url>" - contributor's ORCID, e.g. "0000-0002-1825-0097" or "https://orcid.org/0000-0002-1825-0097"
# ror_id = "<url>"            - ROR identifier of home organisation, e.g. "https://ror.org/04fa4r544"

[[vocabs.photocatalysis_example.id_range]]
first_id = 1
last_id = 5000
gh_name = "nmoust"
orcid = "0000-0002-6242-2167"
ror_id = "https://ror.org/029hg0311"

[[vocabs.photocatalysis_example.id_range]]
first_id = 5001
last_id = 5020
gh_name = "unknown"
orcid = ""
ror_id = ""

# Continue with as many [[myvocab.idrange]] sections as needed.
