# This action runs on merging of PR to main.
#
# Note that we directly publish to gh-pages without a gh-pages branch.
# Be sure to select "GitHub Actions" under Settings > Pages > Build and deployment: Source
#
# Checks: Passes zizmor --nitpicky checks (zizmor 1.19.0)

name: Build docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_PROGRESS_BAR: "off"
  LOGLEVEL: "DEBUG"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build documentation for gh-pages
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Using fetch-depth 0 is the only way to get all tags which are needed for building docs.
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip

          # install tagged version
          python -m pip install .[docs]

      - name: Build Sphinx documentation (website)
        run: |
          sphinx-build -b html --nitpicky --fail-on-warning --keep-going docs docs/_build/html

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: 'docs/_build/html'

  publish:
    name: Publish documentation on gh-pages
    needs: build
    permissions:
      id-token: write   # to verify the deployment originates from an trusted source
      pages: write      # to write to gh-pages branch
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy updated gh-pages content
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
